Webアプリ開発（カウントボタン対応）
takmita/modern-dx pull request #4
Opened 2022-07-13 07:11 UTC by takmita

2022-07-15 09:12 UTC, hyamakawa requested changes
@takmita 

確認しました。ご確認・ご対応お願いします 🙇 

また、1点質問と対応のお願いです。
clasp.jsonやappsscript.jsonがないのですが、あえて消していますか？
この開発は通常の開発と同様で、動作する環境も含めて作成していただいているので、加工は不要です。極端な話、誰でも、このリポジトリをローカルに落とせば、動作する環境を構築できるというノリで作成してください。

2022-07-15 09:12 UTC, hyamakawa commented on index.html
> +</html>
最後に空の改行を入れてください。

2022-07-15 09:12 UTC, hyamakawa commented on main.js
> +  }
最後に空の改行を入れてください。

2022-07-15 09:12 UTC, hyamakawa commented on index.html
> +      const y = x++
変数名はちゃんと役割が分かるような名前にしてください。

2022-07-15 09:12 UTC, hyamakawa commented on index.html
> +        let x = 1
一緒でもいいのかなと思いましたが、headとbodyとでscriptタグを分けてる理由はなんでしょうか。

2022-07-15 09:12 UTC, hyamakawa commented on index.html
> +        let x = 1
初期値1になってますが、初期表示からボタンを1度クリックすると 0 から 2 になりそうな気がするのですが、ちゃんとカウントアップしますか？

2022-07-15 09:12 UTC, hyamakawa commented on index.html
> +        let x = 1
こちらも変数名は意識して付け直してください。

2022-07-15 09:12 UTC, hyamakawa commented on index.html
> +  <script>
bodyタグの中、インデントをつけてください。

2022-07-15 09:12 UTC, hyamakawa commented on index.html
> +  <label for="text1">カウンター：</label>
for属性のことを知れました、ありがとうございます！

2022-07-15 09:34 UTC, takmita commented on index.html
> +      const y = x++
変数名を見直しました。

2022-07-15 09:34 UTC, takmita commented on index.html
> +</html>
対応しました。
理由）テキストファイルとは、いくつかの行の集合である。そして、行とは改行コードで区切られるまでの、一連のテキストデータの連続である。

2022-07-15 09:37 UTC, takmita commented on index.html
> +        let x = 1
変数名を見直しました。

2022-07-15 09:53 UTC, takmita commented on index.html
> +        let x = 1
scriptをheadとbodyに分けた理由ですが、カウンターの初期値を設定する場所（初期処理）として、ヘッダーが良いのかな、と思って、そうしました。しかし、ネットであらためて調べましたが、処理をheadに書くべきではない（ファイルリードはあり）と理解しました。なのでbodyの先頭に異動します。

2022-07-15 10:01 UTC, takmita commented on index.html
> +  <label for="text1">カウンター：</label>
カウンターの初期値を１にして、インクリメントを couter++としていたので、正しくカウントされていました。
しかし、表示の初期値０と同じにしないと分かりにくい、と理解したので、今回、見直しました。

2022-07-15 10:02 UTC, takmita commented on index.html
> +  <script>
インデントを付けました。

2022-07-15 10:03 UTC, takmita commented on index.html
> +        let x = 1
カウンターの初期値を１にして、インクリメントを couter++としていたので、正しくカウントされていました。 しかし、表示の初期値０と同じにしないと分かりにくい、と理解したので、今回、見直しました。

2022-07-15 10:09 UTC, takmita commented on main.js
> +  }
空白行を入れました。

2022-07-15 10:17 UTC, takmita commented
@hyamakawa 
レビュー指摘を一通り、対応しました。確認をお願いします。

>また、1点質問と対応のお願いです。clasp.jsonやappsscript.jsonがないのですが、あえて消していますか？

以下の通り消してはいない認識です。何か対応が必要でしょうか。

**メインブランチ**
<img width="779" alt="image" src="https://user-images.githubusercontent.com/67588651/179203268-e7e4223a-9b4f-4d2c-b359-67710a6ada22.png">

**ローカルリポジトリ**
![image](https://user-images.githubusercontent.com/67588651/179203300-78bc1cce-0301-4c90-a1b5-4e4a3458d34c.png)

2022-07-15 13:15 UTC, hyamakawa reviewed
@takmita 確認しました。追加でコメントしたので、ご確認お願いします。

2022-07-15 13:15 UTC, hyamakawa commented on index.html
> +    <script>
<script>タグを二つに分ける理由はなんでしょうか。。

やってることを見てると、bodyタグ内下部のscriptタグにマージしてもいいように感じるのですが。

2022-07-15 13:15 UTC, hyamakawa commented on index.html
> +      let start_counter = 0
変数名をスネーク形式にした理由はなんでしょうか。。

各言語によってどういう形式で変数名を決めるかは違うのかも知れませんが、少なくともjs界隈では基本はキャメル、DB項目にスネークという慣習をよくみます。

2022-07-15 13:22 UTC, hyamakawa commented
@takmita 

また、 `clasp.jsonやappsscript.json` に関してですが、コメントありがとうございます。
コメント内容を見る限り、プロジェクトには存在はしている。
けれど、masterにすでにpushされているから、今回のプルリクに差分として出てきていないということですかね。
それでしたら、特に対応はありません。

ただプルリクの前提を把握することは難しいです。
課題で想定するプルリク差分と異なる場合はコメントなりしていただけると
スムーズなレビューができるかと思いますので、よろしくお願いしますっ。
（今回だと1-1は課題最初のプルリクなので、本来なら `clasp.json` `appsscript.json` は差分として出てくるべきもの）

2022-07-17 01:02 UTC, takmita commented
> 
> また、1点質問と対応のお願いです。 clasp.jsonやappsscript.jsonがないのですが、あえて消していますか？ この開発は通常の開発と同様で、動作する環境も含めて作成していただいているので、加工は不要です。極端な話、誰でも、このリポジトリをローカルに落とせば、動作する環境を構築できるというノリで作成してください。

今回のプルリクは、最初に誤って自分でマージしてしまっため、rebaseでプルリクを作り直したのですが、clasp.jsonとappsscript.jsonを対象にしてなかったです。そのため、差分が現れませんでした。自分が新規で作ったファイルにしか意識がなく、環境ファイルに意識が向いてなかったということで、理解不足でした。

2022-07-17 01:15 UTC, takmita commented on index.html
> +      let start_counter = 0
キャメルに変更します。迷ったのですが、確認不足でした。

2022-07-17 01:42 UTC, takmita commented on index.html
> +    <script>
カウンタの初期値ゼロをセットするタイミングが、onclick="clickBtnAdd()より前にあるべきだ、と思って、<script>タグを二つに分けました。しかし、２つ目の<script>タグの中（関数の直上）で初期化するように変更しました。処理順序は以下の通りとなるので問題なし、と理解しました。

- 最初に<script>タグを含め<body>タグの中身の全てがロードされる。
- その際、<script>タグの中の、カウンター初期が行われる。
- web画面から、カウントボタンを押すと、onclick="clickBtnAdd()"が実行される

[参考にしたリンク](https://qiita.com/yoshida3/items/a6bb806b1791c6aa3906)

2022-07-17 01:49 UTC, takmita commented
> 確認しました。追加でコメントしたので、ご確認お願いします。

@hyamakawa 対応が終わりましたので、再度、確認をお願いします。

2022-07-17 23:26 UTC, hyamakawa commented
@takmita LGTM、お疲れ様でした 🙆‍♂️

2022-07-19 04:40 UTC, merged