課題2-1 カウンタの値をDBに書き込む
takmita/modern-dx pull request #7
Opened 2022-07-29 02:39 UTC by takmita

@hyamakawa レビューをお願いします。

補足１．カウンターを更新するスプレッドシートの格納場所は以下です。
　https://drive.google.com/drive/folders/1wZLAEBkVc-0BhEec-fO7R753BN1P8lQa

補足２．SpreadsheetApp.openById(id).getSheetByName("シート1");　と
　　　　ss.getRange("A1").setValue([e])　を　main.jsに書いています。
最初は、この２つをindex.htmlに書こうとしましたが、
スプレッドシートの読み込みが、not defineとなり、それを解消できなかったためです。
正しく書けば、index.htmlで全てやれたはず、でしょうか。

2022-07-29 09:22 UTC, hyamakawa requested changes
@takmita 確認しました。コメントしましたので、ご確認・ご対応お願いいたしますっ。

2022-07-29 09:22 UTC, hyamakawa commented on index.html
> +      <input type="text" value=00000  name="counter" id="counter" maxlength="5" class="class_A"/>
`value=00000` これはなんでしょうか？
`value=0` ではダメだったのでしょうか。

2022-07-29 09:22 UTC, hyamakawa commented on index.html
> +      function addChars( targetNum, setFigure, setChar ) {
なんでこんなことをしてるのかよく分かりませんでした。。
4桁ゼロ埋めの数字をカウンターに表示させる仕様にしたから、こういう関数を作成したということでしょうか。

2022-07-29 09:22 UTC, hyamakawa commented on index.html
> +          .writeSheet(document.forms['formText'].elements['counter'].value);
ここだけ、 `getElementById` 経由でvalueを取得していないのですが、何か理由はありますか？
こういう書き方を試してみたかった？

2022-07-29 09:22 UTC, hyamakawa commented on main.js
> +    ss.getRange("A1").setValue([e])
setValueって配列を引数に期待していましたっけ？

2022-07-29 09:22 UTC, hyamakawa commented on main.js
> +    ss.getRange("A1").setValue([e])
https://developers.google.com/apps-script/reference/spreadsheet/range#setvaluevalue

期待してなさそう。

2022-07-29 09:22 UTC, hyamakawa commented on index.html
> +      <input type="text" value=00000  name="counter" id="counter" maxlength="5" class="class_A"/>
もし4桁ZERO埋めで表示したいのでしたら、変数で持っている値は数字にして、表示する時だけZERO埋めして表示してあげる方がスッキリするかなと思いました。ZERO埋めが必要なのは表示の時だけですよね。計算の時は気にしたくないですよね。

2022-07-30 12:03 UTC, takmita commented on index.html
> +      function addChars( targetNum, setFigure, setChar ) {
２－１の課題ではないのですが、4桁ゼロ埋めの数字をカウンターに表示させる仕様にしたくて、関数を作りました。

2022-07-30 13:07 UTC, takmita commented on index.html
> +      <input type="text" value=00000  name="counter" id="counter" maxlength="5" class="class_A"/>
有効桁数5桁のゼロパディング（ゼロ詰め）した表示にしたくて、value=00000としました。value=0ではゼロパディングされません。

2022-07-30 13:40 UTC, takmita commented on index.html
> +          .writeSheet(document.forms['formText'].elements['counter'].value);
試したと言うより、参考にしたサイトの書き方をそのまま真似ただけです。やりたいことからすれば、先に使っているやり方、getElementById を使うべきだと思います。

2022-07-30 13:41 UTC, takmita commented on index.html
> +      <input type="text" value=00000  name="counter" id="counter" maxlength="5" class="class_A"/>
有効桁数5桁のゼロパディング（ゼロ詰め）した表示にしたくて、value=00000としました。value=0ではゼロパディングされません。

2022-07-30 13:54 UTC, takmita commented on main.js
> +    ss.getRange("A1").setValue([e])
配列にする意味ないですね。修正します。

2022-07-31 04:44 UTC, takmita commented on index.html
> +      <input type="text" value=00000  name="counter" id="counter" maxlength="5" class="class_A"/>
>もし4桁ZERO埋めで表示したいのでしたら、変数で持っている値は数字にして、
>表示する時だけZERO埋めして表示してあげる方がスッキリするかなと思いました。
やりたかったことは、コメントに書かれた通りなのです。しかし、どう改良したらよいか、解りませんでした。とりあえず書き方を変更してみましたが、単に処理をばらしただけ、と理解しています。

2022-07-31 04:50 UTC, takmita commented
@hyamakawa 
１回目レビューの指摘を対応しました。再レビューをお願いします。
更新「カウントアップ」と表示「ゼロパディング」の指摘については、ベストプラクティスが出せたと思っていません。個別に相談させてもらっていいですか。

2022-07-31 23:58 UTC, hyamakawa commented on index.html
> +      <input type="text" value=00000  name="counter" id="counter" maxlength="5" class="class_A"/>
例えば、下記URLに `<?!= HtmlService.createHtmlOutputFromFile('css').getContent(); ?>` というのがあるんですが、
この書き方を利用して、画面表示するときに1を0001にするというメソッドを呼び出すようにすれば、内部は数字で扱って、表示すときだけ加工する、ってことができそうだなと思いました。

https://tonari-it.com/gas-web-app-google-script-run/

2022-07-31 23:58 UTC, hyamakawa commented
@takmita 確認しました。0埋め表示の部分をコメントしたのでご確認・ご対応お願いします。

2022-08-01 00:09 UTC, hyamakawa commented
@takmita 嶋田さんも似た仕様で作っているので、参考にしてみてはいかがでしょうか。

https://github.com/k-shimada-esm/modernChallenge/pull/3

2022-08-12 06:17 UTC, takmita commented on index.html
> +      <input type="text" value=00000  name="counter" id="counter" maxlength="5" class="class_A"/>
@hyamakawa   
>画面表示するときに1を0001にするというメソッドを呼び出すようにすれば

cssファイルを外部ファイルに切り出すようにしました。
しかし、ゼロ詰めのメソッドを表示すときだけ呼び出して加工する、やり方を、
理解することはできませんでした。今回は、嶋田さんの書き方を参考に、ゼロ詰めを簡素化しました。
一旦、これで、再レビューをお願いします。

2022-08-12 10:11 UTC, hyamakawa commented
@takmita lgtm 🗻

2022-08-15 00:45 UTC, merged