Webアプリ開発2-2  書き込んだカウンタを表示する
takmita/modern-dx pull request #8
Opened 2022-08-15 05:08 UTC by takmita

@hyamakawa 
確認をお願いします。
https://script.google.com/macros/s/AKfycbxmyl5--XDUGCTP7UEwc1h-2ASvxYnp7pR5u9hwNWU/dev

![image](https://user-images.githubusercontent.com/67588651/184579689-2412bd46-a27a-4ceb-b3fa-7e1129726766.png)

2022-08-15 05:57 UTC, hyamakawa requested changes
@takmita 確認しました。コメントしましたのでご確認・ご対応お願いいたします。

2022-08-15 05:57 UTC, hyamakawa commented on index.html
> +      <button onclick="clickBtnShow()" class="class_btn_show">表示</button>
やることが微妙に違ってます。ボタンではないです。

> 2-2. 前回保存時のカウンターを表示できるようにする
> 画面初期表示時、再読み込み時にスプレッドシート のデータを画面表示する
> 続きからカウントアップできるようにする

⬆︎ スキルカリキュラム予想より

2022-08-16 01:12 UTC, takmita commented on index.html
> +      <button onclick="clickBtnShow()" class="class_btn_show">表示</button>
@hyamakawa 
>画面初期表示時、再読み込み時にスプレッドシート のデータを画面表示する

ですね。見直します。

2022-08-16 09:01 UTC, takmita commented on index.html
> +      <button onclick="clickBtnShow()" class="class_btn_show">表示</button>
@hyamakawa 
見直しました。再度、確認をお願いします。
![image](https://user-images.githubusercontent.com/67588651/184840544-b3cb1a56-618c-4eac-a9fa-a1979922a9bd.png)

https://script.google.com/macros/s/AKfycbxmyl5--XDUGCTP7UEwc1h-2ASvxYnp7pR5u9hwNWU/dev

[スプレッドシート](https://docs.google.com/spreadsheets/d/1hSnXqpaT9qjTz5FWFWtez0TuGVQcSywFhHz8KtYiaYo/edit#gid=0)

2022-08-16 10:50 UTC, hyamakawa commented on index.html
> +      <button onclick="clickBtnShow()" class="class_btn_show">表示</button>
@takmita 

```
document.getElementById("counter").value = ("0000" + counter).slice(-5);  
```

こんな感じのロジックが散見されるので、共通化したな〜とはおもいつつも、やりすぎても次にいけなくなってしまうので、気に留めておくくらいでお願いしますっ！

2022-08-16 10:50 UTC, hyamakawa commented
@takmita lgtm🍟

2022-08-17 13:23 UTC, takmita commented on index.html
> +      <button onclick="clickBtnShow()" class="class_btn_show">表示</button>
これは最初のゼロパディングを関数化していたときからの指摘と同じですかね。その指摘では、関数呼び出しを、処理(html？）から表示(CSS？）で行うようにしたら、いう内容に理解しましたが、その対応方法が考えつきませんでした。

2022-08-17 13:24 UTC, merged