web-app-dev-3-1  Vue.jsを使う
takmita/modern-dx pull request #9
Opened 2022-08-21 03:12 UTC by takmita

@hyamakawa
レビューをお願いします。同じUIと機能で、Vue.js を使ったコードに書き換えています。
![image](https://user-images.githubusercontent.com/67588651/185773661-be56a26b-360f-4b7c-bfd2-c684f40c83e2.png)
https://script.google.com/macros/s/AKfycbxmyl5--XDUGCTP7UEwc1h-2ASvxYnp7pR5u9hwNWU/dev
[スプレッドシート](https://docs.google.com/spreadsheets/d/1hSnXqpaT9qjTz5FWFWtez0TuGVQcSywFhHz8KtYiaYo/edit#gid=0)

2022-08-23 23:30 UTC, takmita commented
@hyamakawa ＠見ていただいていますかね。宜しくお願いします。

2022-08-24 01:35 UTC, hyamakawa requested changes
@takmita すみません、漏れていました。
確認しコメントしたので、ご確認・ご対応よろしくお願いいたします。

2022-08-24 01:35 UTC, hyamakawa commented on js.html
> +  google.script.run.withSuccessHandler(counterShow).readSheet();
Webアプリを読み込んだ時に `counterShow ` を実行したくてこのような形になっているという理解でよろしいでしょうか。もしそうだとすると、Vueのライフサイクルを使えば、もう少しスッキリかけると思います。
createdやmountedあたりを使うことになるかなと思います。
そうするとこんな感じになると思いますので修正してみてください。

``` javascript
<script>
new Vue({
  el: '#app',
  data: {
        ...
  },
  created () {
    ...
  },
  methods: {
    ...
  }
})
</script>
```

2022-08-24 01:35 UTC, hyamakawa commented on index.html
> +      <input type="text" v-model.number="counter" maxlength="5" class="class_A"/>
`v-model.number` これは数字の制約をつけているということですよね？
でも、counterはゼロ埋めした値が入るので、型的には文字列ですよね。
辻褄があってなさそうに見えました。

2022-08-24 03:57 UTC, takmita commented on js.html
> +  google.script.run.withSuccessHandler(counterShow).readSheet();
@hyamakawa 
ライフサイクルのマウントとクリエイトを最初に使ったのですが、どうしても表示がされない、という事象を解決できませんでした。値が取れていることはコンソールログで確認が取れています。this counter = ssContener というコードを書きました。他の方達は、ちゃんと表示がされたということなんですね。

2022-08-24 04:15 UTC, hyamakawa commented on js.html
> +  google.script.run.withSuccessHandler(counterShow).readSheet();
そうですね。GASであろうと変わりません。
ライフサイクルとは別の部分で不具合があったのかもしれませんね。

2022-08-24 14:12 UTC, takmita commented on index.html
> +      <input type="text" v-model.number="counter" maxlength="5" class="class_A"/>
ゼロ埋めして文字列にしているので、Numberを削除します。

2022-08-27 02:27 UTC, takmita commented on js.html
> +  google.script.run.withSuccessHandler(counterShow).readSheet();
@hyamakawa
試行錯誤したのですが、うまくいかないので、アドバイスください。
mountedでgoogle.script.run を使ってスプレッドシートから値を取得。counterの値の置き換えが
できると考えてコードを書き替えてみました。事象としては以下の通りです。
１．google.script.run のなかの this.counter = ssCounter; (11行目)で、counterが置き換わらない。
　　ssCounterに値が取得できていることはコンソールログで確認がとれている(10行目)。
２．google.script.run のそとで this.counter = "77777"と書くと、counterは"77777"に置き換わる。
３．しかし、google.script.run のそとではgoogle.script.runで取得した ssCounterを受け取れない（空白）。
４．別途、ログをみると、google.script.run が13行目（いまはコメント）の処理より、あとで動いている。
![image](https://user-images.githubusercontent.com/67588651/187010587-4175932f-64ee-4ccc-9612-4ea90a1e36a8.png)

![image](https://user-images.githubusercontent.com/67588651/187010602-9fe51609-4f21-41bf-a5d6-f27ad8a73af2.png)

2022-08-27 02:59 UTC, takmita commented on js.html
> +  google.script.run.withSuccessHandler(counterShow).readSheet();
@hyamakawa 
ご参考ですが、最初のプルリク時のコードはこれです。一通りの機能はしていました。
![image](https://user-images.githubusercontent.com/67588651/187011639-92bac6dd-eacb-4bc8-97fc-ec99ad66805a.png)

スプレッドシートからの初期表示は、直接、data句で「値」を送って実現できていたので、mountedは
使ってなかったです。それをライフサイクル（mounted）を使い、その中で、やった方が良い、
という指摘だったのですかね。

2022-08-29 07:40 UTC, hyamakawa commented on js.html
> +  google.script.run.withSuccessHandler(counterShow).readSheet();
@takmita 

> 別途、ログをみると、google.script.run が13行目（いまはコメント）の処理より、あとで動いている。

コチラに関しては同期、非同期処理の話になります。
mounted自体は readSheet()を実行して終わります。
readSheet()の実行が終わって、スプレッドシートから取得した値がフロントエンドに返ってきたら、10~11行目が動いています。
これを回避するにはasync awaitなどを駆使する必要があって、それは後々ある課題で着手する予定になってます。

2022-08-29 07:45 UTC, hyamakawa commented on js.html
> +  google.script.run.withSuccessHandler(counterShow).readSheet();
@takmita 

> google.script.run のなかの this.counter = ssCounter; (11行目)で、counterが置き換わらない。

11行目に書いている `this.counter = ssCounter` の this.counter は data部のcounter を指せてますでしょうか。
おそらく指せてないのかなと思います。
javascriptにおいてthisは扱いが難しい部分があるので、一度ログで確認するなどしてみてください。
その次の対応としては、withSuccessHandlerの中で設定処理を書くのではなく、withSuccessHandler内では関数呼び出しだけにして、呼び出した関数の中で今実装している設定処理を書いてみるとうまくいくような気がします。

2022-08-29 13:38 UTC, takmita commented on js.html
> +  google.script.run.withSuccessHandler(counterShow).readSheet();
@hyamakawa 
>withSuccessHandler内では関数呼び出しだけにして、

この対応で動作しました。
このやり方も試していたはずなのですが、ちゃんと対応できていなかったようです。
今回は、うまく対応できたのだと思います。確認をお願いします。

ちなみに、動作はしたのですが、以下のようなワーニングが出ました。
``DevTools failed to load source map: Could not load content for chrome-extension://gpmlagmcbcnjhkdjiofoenkfbaclgjkk/content-scripts/identity-protection/compat.module.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
``

chromeの拡張機能が影響しているようだったので確認してみると、㏋（自分のPC）のセキュリティ機能が入っていており、それを外してみるとワーニングを消すことができました。色々ありますね。
![image](https://user-images.githubusercontent.com/67588651/187213267-4bc70b1a-9e4b-4b8d-a5ca-1150c60d1e0e.png)

2022-08-30 03:21 UTC, hyamakawa approved these changes
@takmita 

動くようになってよかったですっ。lgtm 🎂

2022-08-30 11:45 UTC, merged